export const BEGIN_LOAD_SERACH_ENGINE_OPTIONS = "BEGIN_LOAD_SERACH_ENGINE_OPTIONS";
export const LOAD_SERACH_ENGINE_OPTIONS_SUCCESS = "LOAD_SERACH_ENGINE_OPTIONS_SUCCESS";
export const LOAD_SERACH_ENGINE_OPTIONS_ERROR = "LOAD_SERACH_ENGINE_OPTIONS_ERROR";

export const BEGIN_FETCH_RANKS = "BEGIN_FETCH_RANKS";
export const FETCH_RANKS_SUCCESS = "FETCH_RANKS_SUCCESS";
export const FETCH_RANKS_ERROR = "FETCH_RANKS_ERROR";

export const PAGE_CLEAN_UP = "PAGE_CLEAN_UP";
